apply plugin: 'com.android.library'
apply plugin: 'jacoco'

group = 'expo.modules.assistant'
version = '0.1.0'

jacoco {
  toolVersion = '0.8.11'
}

def expoModulesCorePlugin = new File(project(":expo-modules-core").projectDir.absolutePath, "ExpoModulesCorePlugin.gradle")
apply from: expoModulesCorePlugin
applyKotlinExpoModulesCorePlugin()
useCoreDependencies()
useExpoPublishing()

// If you want to use the managed Android SDK versions from expo-modules-core, set this to true.
// The Android SDK versions will be bumped from time to time in SDK releases and may introduce breaking changes in your module code.
// Most of the time, you may like to manage the Android SDK versions yourself.
def useManagedAndroidSdkVersions = false
if (useManagedAndroidSdkVersions) {
  useDefaultAndroidSdkVersions()
} else {
  buildscript {
    // Simple helper that allows the root project to override versions declared by this library.
    ext.safeExtGet = { prop, fallback ->
      rootProject.ext.has(prop) ? rootProject.ext.get(prop) : fallback
    }
  }
  project.android {
    compileSdkVersion safeExtGet("compileSdkVersion", 36)
    defaultConfig {
      minSdkVersion safeExtGet("minSdkVersion", 24)
      targetSdkVersion safeExtGet("targetSdkVersion", 36)
    }
  }
}

android {
  namespace "expo.modules.assistant"
  defaultConfig {
    versionCode 1
    versionName "0.1.0"
  }
  lintOptions {
    abortOnError false
  }
  testOptions {
    unitTests {
      includeAndroidResources = true
      returnDefaultValues = true
      all {
        jacoco {
          includeNoLocationClasses = true
          excludes = ['jdk.internal.*']
        }
      }
    }
  }
}

tasks.register('jacocoTestReport', JacocoReport) {
  dependsOn 'testDebugUnitTest'
  group = 'verification'
  description = 'Generates Jacoco coverage report for unit tests.'

  reports {
    xml.required = true
    html.required = true
  }

  def fileFilter = ['**/R.class', '**/R$*.class', '**/BuildConfig.*', '**/Manifest*.*', '**/*Test*.*', '**/*$*.class']
  def kotlinDebugTree = fileTree(dir: "$buildDir/tmp/kotlin-classes/debug", excludes: fileFilter)
  def javaDebugTree = fileTree(dir: "$buildDir/intermediates/javac/debug/classes", excludes: fileFilter)

  classDirectories.setFrom(files([kotlinDebugTree, javaDebugTree]))
  sourceDirectories.setFrom(files(['src/main/java']))
  executionData.setFrom(fileTree(dir: buildDir, includes: ['jacoco/testDebugUnitTest.exec', 'outputs/unit_test_code_coverage/debugUnitTest/testDebugUnitTest.exec']))
}

dependencies {
  testImplementation 'junit:junit:4.13.2'
  testImplementation 'io.mockk:mockk:1.13.10'
  testImplementation 'org.robolectric:robolectric:4.12.2'
  testImplementation 'org.jetbrains.kotlin:kotlin-test:1.9.24'
  testImplementation 'androidx.test:core:1.5.0'
  testImplementation 'androidx.test.ext:junit:1.1.5'
}
