// ============================================================
// !!! SPIKE MODE: HAND-EDITED — DO NOT RUN `expo prebuild` !!!
// This file has been hand-edited with inlined spike intents for
// issue #30 research. Running `expo prebuild --platform ios` will
// revert these edits. See spike/assistant-schemas-30/README.md.
//
// Spike intents inlined (rather than in separate file) because the
// separate file would require manual Xcode project registration —
// inlining lets us bypass pbxproj surgery for the throwaway spike.
// ============================================================
//
// AUTO-GENERATED by expo-assistant. Do not edit by hand.
// Regenerated on every `expo prebuild --platform ios`.

import AppIntents
import ExpoAssistant
import Foundation

@available(iOS 16.0, *)
public struct ProjectEntity: AppEntity, IndexedEntity, Identifiable {
    public let id: String
    @Property(title: "Title")
    public var title: String

    @Property(title: "Summary")
    public var summary: String

    public static var typeDisplayRepresentation: TypeDisplayRepresentation = "Project"
    public static var defaultQuery = ProjectQuery()

    public var displayRepresentation: DisplayRepresentation {
        DisplayRepresentation(title: "\(title)")
    }

    public init(from dict: [String: Any]) {
        self.id = (dict["id"] as? String) ?? ""
        self.title = (dict["title"] as? String) ?? ""
        self.summary = (dict["summary"] as? String) ?? ""
    }

    public func asDictionary() -> [String: Any] {
        return [
            "id": id,
            "title": title,
            "summary": summary
        ]
    }

    public static func == (lhs: ProjectEntity, rhs: ProjectEntity) -> Bool {
        return lhs.id == rhs.id
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(id)
    }
}

@available(iOS 16.0, *)
public struct ProjectQuery: EntityStringQuery {
    public init() {}

    public func entities(for identifiers: [ProjectEntity.ID]) async throws -> [ProjectEntity] {
        let raw = await (ExpoAssistantModule.shared?.entityResolver.resolve(
            typeName: "Project",
            kind: "for",
            payload: ["ids": identifiers]
        ) ?? [])
        return raw.map { ProjectEntity(from: $0) }
    }

    public func entities(matching string: String) async throws -> [ProjectEntity] {
        let raw = await (ExpoAssistantModule.shared?.entityResolver.resolve(
            typeName: "Project",
            kind: "matching",
            payload: ["search": string]
        ) ?? [])
        return raw.map { ProjectEntity(from: $0) }
    }

    public func suggestedEntities() async throws -> [ProjectEntity] {
        let raw = await (ExpoAssistantModule.shared?.entityResolver.resolve(
            typeName: "Project",
            kind: "suggested",
            payload: [:]
        ) ?? [])
        return raw.map { ProjectEntity(from: $0) }
    }
}

@available(iOS 16.0, *)
public struct OpenProjectIntent: AppIntent {
    public static var title: LocalizedStringResource = "Open Project"

    public static var parameterSummary: some ParameterSummary {
        Summary("Open Project \(\.$project)")
    }

    @Parameter(
        title: "Project",
        requestValueDialog: "Which project?"
    )
    public var project: ProjectEntity

    public init() {}

    public func perform() async throws -> some IntentResult {
        await MainActor.run {
            ExpoAssistantModule.shared?.emitIntent(
                id: "open-project",
                parameters: [
                    "project": project.asDictionary()
                ]
            )
        }
        return .result()
    }
}

// MARK: - SPIKE INTENTS (issue #30 research)

@available(iOS 18.0, *)
@AppIntent(schema: .system.search)
public struct SpikeSearchIntent {
    public static var searchScopes: [StringSearchScope] = [.general]
    public var criteria: StringSearchCriteria

    public init() {
        self.criteria = StringSearchCriteria(term: "")
    }

    public func perform() async throws -> some IntentResult {
        let perfStart = Date()
        await MainActor.run {
            ExpoAssistantModule.shared?.emitIntent(
                id: "spike-schema-search",
                parameters: [
                    "criteria": criteria.term,
                    "_perfStartMs": Int(perfStart.timeIntervalSince1970 * 1000)
                ]
            )
        }
        let perfEnd = Date()
        NSLog("[expo-assistant-spike] SpikeSearchIntent.perform() bridge latency: \(Int(perfEnd.timeIntervalSince(perfStart) * 1000))ms")
        return .result()
    }
}

// NOTE: Originally used .system.search but build failed:
//   "Only 1 type per app allowed to conform to Assistant schema identifier
//    'ShowInAppSearchResultsIntent' with version '1.0.0'"
// Switched to .camera.stopCapture (zero-param, AppIntent base — different
// schema identifier so no conflict with SpikeSearchIntent above).
// This is itself a spike finding — apple enforces per-schema-id uniqueness
// at the BINARY level, not just per-macro. Codegen needs prebuild validation
// rejecting duplicate `schema:` values across appShortcuts[].

@available(iOS 18.0, *)
@AppIntent(schema: .camera.stopCapture)
public struct SpikeAssistantOnlyIntent {
    public static let isAssistantOnly: Bool = true

    public init() {}

    public func perform() async throws -> some IntentResult {
        await MainActor.run {
            ExpoAssistantModule.shared?.emitIntent(
                id: "spike-assistant-only",
                parameters: [:]
            )
        }
        NSLog("[expo-assistant-spike] SpikeAssistantOnlyIntent.perform() fired")
        return .result()
    }
}

@available(iOS 16.0, *)
public struct SpikeControlIntent: AppIntent {
    public static var title: LocalizedStringResource = "Spike Control"
    public static var description: IntentDescription? = IntentDescription("Vanilla AppIntent — control case for comparison")

    @Parameter(title: "Query")
    public var query: String

    public init() {}

    public func perform() async throws -> some IntentResult {
        let perfStart = Date()
        await MainActor.run {
            ExpoAssistantModule.shared?.emitIntent(
                id: "spike-control",
                parameters: [
                    "query": query,
                    "_perfStartMs": Int(perfStart.timeIntervalSince1970 * 1000)
                ]
            )
        }
        let perfEnd = Date()
        NSLog("[expo-assistant-spike] SpikeControlIntent.perform() bridge latency: \(Int(perfEnd.timeIntervalSince(perfStart) * 1000))ms")
        return .result()
    }
}

// MARK: - Refresher + Provider

@available(iOS 16.4, *)
@objc(ExpoAssistantParametersRefresher)
public class ExpoAssistantParametersRefresher: NSObject {
    @objc public static func refresh() {
        ExpoAssistantAppShortcuts.updateAppShortcutParameters()
    }
}

@available(iOS 16.0, *)
public struct ExpoAssistantAppShortcuts: AppShortcutsProvider {
    public static var appShortcuts: [AppShortcut] {
        var shortcuts: [AppShortcut] = [
            AppShortcut(
                intent: OpenProjectIntent(),
                phrases: ["Open project in \(.applicationName)", "Open a project in \(.applicationName)", "Show me a project in \(.applicationName)"],
                shortTitle: "Open Project",
                systemImageName: "folder.fill"
            ),
            AppShortcut(
                intent: SpikeControlIntent(),
                phrases: ["Run spike control in \(.applicationName)"],
                shortTitle: "Spike Control",
                systemImageName: "checkmark.circle"
            )
        ]
        if #available(iOS 18.0, *) {
            shortcuts.append(
                AppShortcut(
                    intent: SpikeSearchIntent(),
                    phrases: ["Run spike search in \(.applicationName)"],
                    shortTitle: "Spike Search",
                    systemImageName: "magnifyingglass"
                )
            )
            shortcuts.append(
                AppShortcut(
                    intent: SpikeAssistantOnlyIntent(),
                    phrases: ["Run spike assistant only in \(.applicationName)"],
                    shortTitle: "Spike Assistant Only",
                    systemImageName: "sparkles"
                )
            )
        }
        return shortcuts
    }
}
