// ============================================================
// !!! SPIKE MODE: HAND-EDITED — DO NOT RUN `expo prebuild` !!!
// This file has been hand-edited to wire in spike intents from
// SpikeSchemaIntents.swift for issue #30 research. Running
// `expo prebuild --platform ios` will revert these edits. See
// example/ios/expoassistantexample/SPIKE_TEST_PLAN.md.
// ============================================================
//
// AUTO-GENERATED by expo-assistant. Do not edit by hand.
// Regenerated on every `expo prebuild --platform ios`.
//
// Declares the AppShortcutsProvider for this app. iOS 16+ scans for one
// per app; this file IS that provider. Shortcut entries come from
// `app.json` → `expo.plugins` → expo-assistant → `ios.appShortcuts`.
//
// Shortcuts with a declared `parameters` array get a dedicated typed
// AppIntent struct generated below; everything else falls back to
// `GenericVoiceIntent` shipped by the pod for backwards compatibility.
// Declared enums (ios.enums[]) and entities (ios.entities[]) are
// emitted first as AppEnum / AppEntity-conforming types so the typed
// intent structs can reference them.
//
// Apple framework reference docs for the types used below:
//   AppShortcutsProvider — https://developer.apple.com/documentation/appintents/appshortcutsprovider
//   AppShortcut          — https://developer.apple.com/documentation/appintents/appshortcut
//   AppShortcutPhrase    — https://developer.apple.com/documentation/appintents/appshortcutphrase
//   AppIntent            — https://developer.apple.com/documentation/appintents/appintent
//   @Parameter           — https://developer.apple.com/documentation/appintents/parameter
//   ParameterSummary     — https://developer.apple.com/documentation/appintents/parametersummary
//   IntentResult         — https://developer.apple.com/documentation/appintents/intentresult
//   TypeDisplayRepresentation — https://developer.apple.com/documentation/appintents/typedisplayrepresentation
//   DisplayRepresentation — https://developer.apple.com/documentation/appintents/displayrepresentation
//   AppEntity            — https://developer.apple.com/documentation/appintents/appentity
//   EntityStringQuery    — https://developer.apple.com/documentation/appintents/entitystringquery
//   EntityQuery          — https://developer.apple.com/documentation/appintents/entityquery
//
// See AGENTS.md → "Reference docs" in the expo-assistant repo for
// guidance on when to consult each one and what's documented vs
// empirically observed (notably the AppShortcutPhrase
// parameter-type constraint, issue #37).

import AppIntents
import ExpoAssistant
import Foundation

@available(iOS 16.0, *)
public struct ProjectEntity: AppEntity, IndexedEntity, Identifiable {
    public let id: String
    @Property(title: "Title")
    public var title: String

    @Property(title: "Summary")
    public var summary: String

    public static var typeDisplayRepresentation: TypeDisplayRepresentation = "Project"
    public static var defaultQuery = ProjectQuery()

    public var displayRepresentation: DisplayRepresentation {
        DisplayRepresentation(title: "\(title)")
    }

    public init(from dict: [String: Any]) {
        self.id = (dict["id"] as? String) ?? ""
        self.title = (dict["title"] as? String) ?? ""
        self.summary = (dict["summary"] as? String) ?? ""
    }

    public func asDictionary() -> [String: Any] {
        return [
            "id": id,
            "title": title,
            "summary": summary
        ]
    }

    // AppEntity requires Hashable. @Property-wrapped fields don't
    // synthesize Equatable / Hashable automatically, so we provide
    // id-based conformance — every entity is uniquely identified by
    // its id per Apple's AppEntity protocol.
    public static func == (lhs: ProjectEntity, rhs: ProjectEntity) -> Bool {
        return lhs.id == rhs.id
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(id)
    }
}

@available(iOS 16.0, *)
public struct ProjectQuery: EntityStringQuery {
    public init() {}

    public func entities(for identifiers: [ProjectEntity.ID]) async throws -> [ProjectEntity] {
        let raw = await (ExpoAssistantModule.shared?.entityResolver.resolve(
            typeName: "Project",
            kind: "for",
            payload: ["ids": identifiers]
        ) ?? [])
        return raw.map { ProjectEntity(from: $0) }
    }

    public func entities(matching string: String) async throws -> [ProjectEntity] {
        let raw = await (ExpoAssistantModule.shared?.entityResolver.resolve(
            typeName: "Project",
            kind: "matching",
            payload: ["search": string]
        ) ?? [])
        return raw.map { ProjectEntity(from: $0) }
    }

    public func suggestedEntities() async throws -> [ProjectEntity] {
        let raw = await (ExpoAssistantModule.shared?.entityResolver.resolve(
            typeName: "Project",
            kind: "suggested",
            payload: [:]
        ) ?? [])
        return raw.map { ProjectEntity(from: $0) }
    }
}

@available(iOS 16.0, *)
public struct OpenProjectIntent: AppIntent {
    public static var title: LocalizedStringResource = "Open Project"

    public static var parameterSummary: some ParameterSummary {
        Summary("Open Project \(\.$project)")
    }

    @Parameter(
        title: "Project",
        requestValueDialog: "Which project?"
    )
    public var project: ProjectEntity

    public init() {}

    public func perform() async throws -> some IntentResult {
        await MainActor.run {
            ExpoAssistantModule.shared?.emitIntent(
                id: "open-project",
                parameters: [
                    "project": project.asDictionary()
                ]
            )
        }
        return .result()
    }
}

@available(iOS 16.4, *)
@objc(ExpoAssistantParametersRefresher)
public class ExpoAssistantParametersRefresher: NSObject {
    @objc public static func refresh() {
        ExpoAssistantAppShortcuts.updateAppShortcutParameters()
    }
}

@available(iOS 16.0, *)
public struct ExpoAssistantAppShortcuts: AppShortcutsProvider {
    public static var appShortcuts: [AppShortcut] {
        var shortcuts: [AppShortcut] = [
            AppShortcut(
                intent: OpenProjectIntent(),
                phrases: ["Open project in \(.applicationName)", "Open a project in \(.applicationName)", "Show me a project in \(.applicationName)"],
                shortTitle: "Open Project",
                systemImageName: "folder.fill"
            ),
            AppShortcut(
                intent: SpikeControlIntent(),
                phrases: ["Run spike control in \(.applicationName)"],
                shortTitle: "Spike Control",
                systemImageName: "checkmark.circle"
            )
        ]
        if #available(iOS 18.0, *) {
            shortcuts.append(
                AppShortcut(
                    intent: SpikeSearchIntent(),
                    phrases: ["Run spike search in \(.applicationName)"],
                    shortTitle: "Spike Search",
                    systemImageName: "magnifyingglass"
                )
            )
            shortcuts.append(
                AppShortcut(
                    intent: SpikeAssistantOnlyIntent(),
                    phrases: ["Run spike assistant only in \(.applicationName)"],
                    shortTitle: "Spike Assistant Only",
                    systemImageName: "sparkles"
                )
            )
        }
        return shortcuts
    }
}
