// SPIKE: AssistantSchemas runtime behavior verification (issue #30 prep).
//
// This file is hand-written to verify iOS behavior of schema-conformant
// intents under our existing AppShortcutsProvider pipeline. It is NOT
// auto-generated by the plugin — `expo prebuild` will NOT touch this file
// (it lives in the iOS folder but is not in our codegen output path).
//
// Three intents declared:
//   1. SpikeSearchIntent         — @AppIntent(schema: .system.search), used
//                                  for voice extraction test (Spike Q1) +
//                                  cold-start latency test (Spike Q4)
//   2. SpikeAssistantOnlyIntent  — same schema + isAssistantOnly = true,
//                                  used for AppShortcutsProvider phrase
//                                  interaction test (Spike Q3)
//   3. SpikeControlIntent        — vanilla AppIntent (no schema), control
//                                  case for comparison in Q1 and Q4
//
// These are added to ExpoAssistantAppShortcuts.appShortcuts via a hand-edit
// to AppShortcutsBridge.generated.swift (see warning block at top of that
// file). DO NOT run `expo prebuild` while this spike is in flight or the
// edits get reverted.
//
// See SPIKE_TEST_PLAN.md in this folder for the test procedure.

import AppIntents
import ExpoAssistant
import Foundation

// MARK: - Schema intent for voice extraction + cold-start tests

@available(iOS 18.0, *)
@AppIntent(schema: .system.search)
public struct SpikeSearchIntent {
    public static var searchScopes: [StringSearchScope] = [.general]
    public var criteria: StringSearchCriteria

    public init() {
        self.criteria = StringSearchCriteria(term: "")
    }

    public func perform() async throws -> some IntentResult {
        let perfStart = Date()
        await MainActor.run {
            ExpoAssistantModule.shared?.emitIntent(
                id: "spike-schema-search",
                parameters: [
                    "criteria": criteria.term,
                    "_perfStartMs": Int(perfStart.timeIntervalSince1970 * 1000)
                ]
            )
        }
        let perfEnd = Date()
        NSLog("[expo-assistant-spike] SpikeSearchIntent.perform() bridge latency: \(Int(perfEnd.timeIntervalSince(perfStart) * 1000))ms")
        return .result()
    }
}

// MARK: - Schema intent with isAssistantOnly for AppShortcutsProvider interaction test

@available(iOS 18.0, *)
@AppIntent(schema: .system.search)
public struct SpikeAssistantOnlyIntent {
    public static let isAssistantOnly: Bool = true
    public static var searchScopes: [StringSearchScope] = [.general]
    public var criteria: StringSearchCriteria

    public init() {
        self.criteria = StringSearchCriteria(term: "")
    }

    public func perform() async throws -> some IntentResult {
        await MainActor.run {
            ExpoAssistantModule.shared?.emitIntent(
                id: "spike-assistant-only-search",
                parameters: ["criteria": criteria.term]
            )
        }
        NSLog("[expo-assistant-spike] SpikeAssistantOnlyIntent.perform() fired")
        return .result()
    }
}

// MARK: - Control case: vanilla AppIntent for comparison

@available(iOS 16.0, *)
public struct SpikeControlIntent: AppIntent {
    public static var title: LocalizedStringResource = "Spike Control"
    public static var description: IntentDescription? = IntentDescription("Vanilla AppIntent — control case for comparison")

    @Parameter(title: "Query")
    public var query: String

    public init() {}

    public func perform() async throws -> some IntentResult {
        let perfStart = Date()
        await MainActor.run {
            ExpoAssistantModule.shared?.emitIntent(
                id: "spike-control",
                parameters: [
                    "query": query,
                    "_perfStartMs": Int(perfStart.timeIntervalSince1970 * 1000)
                ]
            )
        }
        let perfEnd = Date()
        NSLog("[expo-assistant-spike] SpikeControlIntent.perform() bridge latency: \(Int(perfEnd.timeIntervalSince(perfStart) * 1000))ms")
        return .result()
    }
}
